import '../models/alfabe_model.dart';

List<AlfabeModel> AlfabeList = [
  AlfabeModel(text: 'A', audio: 'assets/audio/alfabe/kid-a.mp3'),
  AlfabeModel(text: 'B', audio: 'assets/audio/alfabe/kid-b.mp3'),
  AlfabeModel(text: 'C', audio: 'assets/audio/alfabe/kid-c.mp3'),
  AlfabeModel(text: 'D', audio: 'assets/audio/alfabe/kid-d.mp3'),
  AlfabeModel(text: 'E', audio: 'assets/audio/alfabe/kid-e.mp3'),
  AlfabeModel(text: 'F', audio: 'assets/audio/alfabe/kid-f.mp3'),
  AlfabeModel(text: 'G', audio: 'assets/audio/alfabe/kid-g.mp3'),
  AlfabeModel(text: 'H', audio: 'assets/audio/alfabe/kid-h.mp3'),
  AlfabeModel(text: 'I', audio: 'assets/audio/alfabe/kid-i.mp3'),
  AlfabeModel(text: 'J', audio: 'assets/audio/alfabe/kid-j.mp3'),
  AlfabeModel(text: 'K', audio: 'assets/audio/alfabe/kid-k.mp3'),
  AlfabeModel(text: 'L', audio: 'assets/audio/alfabe/kid-l.mp3'),
  AlfabeModel(text: 'M', audio: 'assets/audio/alfabe/kid-m.mp3'),
  AlfabeModel(text: 'N', audio: 'assets/audio/alfabe/kid-n.mp3'),
  AlfabeModel(text: 'O', audio: 'assets/audio/alfabe/kid-o.mp3'),
  AlfabeModel(text: 'P', audio: 'assets/audio/alfabe/kid-p.mp3'),
  AlfabeModel(text: 'Q', audio: 'assets/audio/alfabe/kid-q.mp3'),
  AlfabeModel(text: 'R', audio: 'assets/audio/alfabe/kid-r.mp3'),
  AlfabeModel(text: 'S', audio: 'assets/audio/alfabe/kid-s.mp3'),
  AlfabeModel(text: 'T', audio: 'assets/audio/alfabe/kid-t.mp3'),
  AlfabeModel(text: 'U', audio: 'assets/audio/alfabe/kid-u.mp3'),
  AlfabeModel(text: 'V', audio: 'assets/audio/alfabe/kid-v.mp3'),
  AlfabeModel(text: 'W', audio: 'assets/audio/alfabe/kid-w.mp3'),
  AlfabeModel(text: 'X', audio: 'assets/audio/alfabe/kid-x.mp3'),
  AlfabeModel(text: 'Y', audio: 'assets/audio/alfabe/kid-y.mp3'),
  AlfabeModel(text: 'Z', audio: 'assets/audio/alfabe/kid-z.mp3'),
];
